let dir=
[{
        name:'真相短视频：抑郁和不孕的她迎来了光明 ',
        value:'Rb4n'
    },{
        name:'大纪元新闻网',
        value:'2'
    },{
        name:'功夫寻道',
        value:'video/play/1096.html'
    },
    {
        name:'传奇时代',
        value:'pVRc'
    },
    {
        name:'过年',
        value:'wBZT'
    },
    {
        name:'艺考',
        value:'TnkQ'
    },
    {
        name:'小磊历险记',
        value:'q183'
    },
    {
        name:'终极目的',
        value:'npXG'
    },
    {
        name:'街对面的烛光',
        value:'7CxZ'
    },
    {
        name:'希望之声直播',
        value:'RjrP'
    },
    {
        name:'铁证如山',
        value:'video/play/1080.html'
    },
    {
        name:'九评之一',
        value:'video/play/4.html'
    },
    {
        name:'传奇时代 义诉',
        value:'video/play/1040.html'
    },
    {
        name:'共产主义的终极目的',
        value:'video/play/1035.html'
    },
    {
        name:'新唐人中国频道直播',
        value:'v.php?id=ntd'
    },
    {
        name:'新唐人亚太台直播',
        value:'v.php?id=ntd-mlt'
    },
    {
        name:'每日精选新闻',
        value:'news.php'
    }
]